; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = rpipico2

[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower
board = rpipico2
framework = arduino
upload_port = /Volumes/RP2350
lib_archive = no
lib_deps = 
   adafruit/Adafruit TinyUSB Library@^3.7.7
   https://github.com/pschatzmann/arduino-audio-tools
build_flags =
   -DUSE_TINYUSB
