; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = rpipico2

[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower
board = rpipico2
framework = arduino
upload_port = /Volumes/RP2350
lib_archive = no
lib_deps = 
   https://github.com/pschatzmann/arduino-audio-tools
   fortyseveneffects/MIDI Library
   https://github.com/the-real-mcarn/PT6302
build_flags =
   -DUSE_TINYUSB
   -Iinclude
board_build.arduino.earlephilhower.usb_manufacturer = Pioneer Corporation
board_build.arduino.earlephilhower.usb_product = Pioneer CDJ-850
board_build.arduino.earlephilhower.usb_vid = 0x08E4
board_build.arduino.earlephilhower.usb_pid = 0x0157
